import = [
"~/.config/alacritty/themes/tokyo-night-storm.toml",
"~/.config/alacritty/themes/tango_dark.toml",
"~/.config/alacritty/themes/dracula_plus.toml",
"~/.config/alacritty/themes/ayu_dark.toml",
"~/.config/alacritty/themes/falcon.toml",
"~/.config/alacritty/themes/palenight.toml",

#"~/.config/alacritty/themes/catppuccin_latte.toml",
#"~/.config/alacritty/themes/enfocado_light.toml",
]

live_config_reload = true

[window]
dimensions = { columns = 110, lines = 36}
opacity = 0.98
padding = { x = 5, y = 15 }
# decoration = "None"

[font]
normal = { family = "MesloLGS NF", style = "regular" }
size = 11.00

